node{
    deleteDir()
    dir("build-config"){
        checkout scm
    }
    if("${MANIFEST_FILE_URL}" == null || "${MANIFEST_FILE_URL}" == "null" || "${MANIFEST_FILE_URL}" == ""){
        stage("Generate Manifest"){
            timestamps{
                withEnv([
                    "branch=${env.branch}",
                    "date=current",
                    "timezone=-0500"
                ]){
                    sh '''#!/bin/bash -ex
                    pushd $WORKSPACE
                    ./build-config/build-release-tools/HWIMO-BUILD build-config/build-release-tools/application/generate_manifest.py \
                    --branch "$branch" \
                    --date "$date" \
                    --timezone "$timezone" \
                    --builddir b \
                    --force \
                    --jobs 8

                    arrBranch=($(echo $branch | tr "/" "\n"))
                    slicedBranch=${arrBranch[-1]}
                    manifest_file=$(find -maxdepth 1 -name "$slicedBranch-[0-9]*" -printf "%f\n")
                    mv $manifest_file manifest
                    '''

                    archiveArtifacts 'manifest'
                    stash name: 'manifest', includes: 'manifest'
                    env.stash_manifest_name = 'manifest'
                    env.stash_manifest_path = 'manifest'
                }
            }
        }
    }
    stage("Test"){
        load("build-config/jobs/function_test/function_test.groovy")
    }
}
