import groovy.transform.Field;
@Field def shareMethod
node{
    deleteDir()

    // checkout RackHD and check if there is change under RackHD/packer
    checkout(
    [
        $class: 'GitSCM',
        branches: [[name: 'master']],
        doGenerateSubmoduleConfigurations: false,
        extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'packer/(.*/)?.*']],
        submoduleCfg: [],
        userRemoteConfigs: [[url: 'https://github.com/RackHD/RackHD/']]
    ]
    )

    checkout scm
    shareMethod = load("jobs/ShareMethod.groovy")
}

timestamps{
    lock("vagrant_build"){
        String label_name = "packer_vagrant"
        lock(label:label_name,quantity:1){
            resources_name = shareMethod.getLockedResourceName(label_name)
            if(resources_name.size>0){
                node_name = resources_name[0]
            }
            else{
                error("Failed to find resource with label " + label_name)
            }
            node(node_name){
                deleteDir()
                dir("on-build-config"){
                    // Clean Up
                    checkout scm
                    sh  ''' ./jobs/build_vagrant/cleanup_vbox.sh '''
                }
                def url = "https://github.com/RackHD/RackHD.git"
                def branch = "master"
                def targetDir = "RackHD"
                shareMethod.checkout(url, branch, targetDir)
                withEnv([
                    "OS_VER=${env.OS_VER}",
                    "BUILD_STAGE=BUILD_TEMPLATE",
                    "BUILD_TYPE=virtualbox",
                    "PACKER_CACHE_DIR=$HOME/packer_cache"
                ]){
                    timeout(70){
                        try{
                            sh '''#!/bin/bash -ex
                            pushd $WORKSPACE/RackHD/packer
                            ./HWIMO-BUILD
                            popd
                            '''
                        } finally{
                            archiveArtifacts "RackHD/packer/output-*/*.*"
                            sh '''#!/bin/bash -x
                            set +e
                            pushd $WORKSPACE
                            ./on-build-config/jobs/build_vagrant/cleanup_vbox.sh
                            popd
                            rm -rf $WORKSPACE/RackHD/packer/output-*
                            '''
                        }
                    }
                }
            }
        }
    }
}

