---
- hosts: deb
  roles:
    - aptget-update
    - for-jenkins-connection
    - install-fundamental-tools
    - install-package-for-build
    - install-rackhd-dependency
    - install-python-tools
    - install-ansible
    - tmp-clean
    - sync-clock
